stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: avazuretest.azurecr.io/pipeline-test
      pushRemote: true
      registry: avazuretest.azurecr.io
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
timeout: 60
notification:
  recipients:
  - recipient: '#azure-rancher'
    notifier: c-jxx5b:n-xzk2m
  condition:
  - Success
  - Failed
